// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-demo/greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: GreetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/qrcode/get",
				Handler: GetQrCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/qrcode/scan",
				Handler: ScanQrCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/qrcode/confirm",
				Handler: ConfirmQrCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/qrcode/check/:qrCode",
				Handler: CheckQrCodeHandler(serverCtx),
			},
		},
	)
}
