// Code generated by goctl. DO NOT EDIT.
package types

type HelloReq struct {
	Name string `form:"name"`
}

type HelloResp struct {
	Message string `json:"message"`
}

type GetQrCodeReq struct {
	DeviceId string `json:"deviceId"`
}

type GetQrCodeResp struct {
	QrCode string `json:"qrCode"`
}

type ScanQrCodeReq struct {
	QrCode string `json:"qrCode"`
	UserId string `json:"userId"`
}

type ScanQrCodeResp struct {
	Token string `json:"token"`
}

type ConfirmQrCodeReq struct {
	QrCode string `json:"qrCode"`
	Token  string `json:"token"`
}

type ConfirmQrCodeResp struct {
}

type CheckQrCodeReq struct {
	QrCode string `path:"qrCode"`
}

type CheckQrCodeResp struct {
}
